"""add priority field

Revision ID: 00756764ceed
Revises: 12e76c92d6bd
Create Date: 2026-03-25 08:17:22.550500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00756764ceed'
down_revision: Union[str, Sequence[str], None] = '12e76c92d6bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('priority', sa.Enum('HIGHT', 'MEDIUM', 'LOW', name='cardprioroty', native_enum=False), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'priority')
    # ### end Alembic commands ###
