"""fix Attachments model

Revision ID: 12e76c92d6bd
Revises: afd2b3d462ab
Create Date: 2026-03-24 08:17:04.936224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12e76c92d6bd'
down_revision: Union[str, Sequence[str], None] = 'afd2b3d462ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('stored_filename', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachments', 'stored_filename')
    # ### end Alembic commands ###
