"""add model projects

Revision ID: 292814d45d15
Revises: b2c3d4e5f6a7
Create Date: 2026-08-27 09:42:29.484778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '292814d45d15'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_assignees_user_id'), table_name='card_assignees')
    op.drop_index(op.f('ix_project_members_user_id'), table_name='project_members')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_card_assignees_user_id'), 'card_assignees', ['user_id'], unique=False)
    # ### end Alembic commands ###
