"""fix_assigned_to_typo

Revision ID: 3536a997b362
Revises: e86feb4d7617
Create Date: 2026-03-16 15:50:14.857396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3536a997b362'
down_revision: Union[str, Sequence[str], None] = 'e86feb4d7617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('assigned_to', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('cards_asigned_to_fkey'), 'cards', type_='foreignkey')
    op.create_foreign_key(None, 'cards', 'users', ['assigned_to'], ['user_id'], ondelete='SET NULL')
    op.drop_column('cards', 'asigned_to')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('asigned_to', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.create_foreign_key(op.f('cards_asigned_to_fkey'), 'cards', 'users', ['asigned_to'], ['user_id'], ondelete='SET NULL')
    op.drop_column('cards', 'assigned_to')
    # ### end Alembic commands ###
