"""fix_assigned_to_typo

Revision ID: 5cd28c8a5dd0
Revises: 3536a997b362
Create Date: 2026-03-16 15:55:19.494612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cd28c8a5dd0'
down_revision: Union[str, Sequence[str], None] = '3536a997b362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'assigned_to',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'assigned_to',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
