"""fix priority field

Revision ID: a17476da2fb3
Revises: 00756764ceed
Create Date: 2026-03-25 10:49:08.590651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a17476da2fb3'
down_revision: Union[str, Sequence[str], None] = '00756764ceed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE cardpriority AS ENUM ('LOW', 'MEDIUM', 'HIGHT')")
    op.alter_column('cards', 'priority',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('HIGHT', 'MEDIUM', 'LOW', name='cardpriority'),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::character varying"))
    op.execute(
        "ALTER TABLE cards ALTER COLUMN priority TYPE cardpriority USING priority::text::cardpriority"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE cards ALTER COLUMN priority TYPE VARCHAR")
    op.alter_column('cards', 'priority',
               existing_type=sa.Enum('HIGHT', 'MEDIUM', 'LOW', name='cardpriority'),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::character varying"))
    op.execute("DROP TYPE cardpriority")
    # ### end Alembic commands ###
