"""add_archive_column

Revision ID: d310ba88c255
Revises: d07da2cb0c04
Create Date: 2026-03-30 10:11:10.787015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd310ba88c255'
down_revision: Union[str, Sequence[str], None] = 'd07da2cb0c04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False))
    op.drop_constraint(op.f('comments_user_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.add_column('events', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('events', sa.Column('card_id', sa.UUID(), nullable=True))
    op.execute("CREATE TYPE eventtype AS ENUM ('CARD_CREATED', 'CARD_EDITED', 'CARD_MOVED', 'CARD_ARCHIVED', 'CARD_RESTORED', 'COMMENT_ADDED', 'COMMENT_EDITED', 'COMMENT_DELETED', 'ATTACHMENT_ADDED', 'ATTACHMENT_DELETED')")
    op.add_column('events', sa.Column('event_type', postgresql.ENUM('CARD_CREATED', 'CARD_EDITED', 'CARD_MOVED', 'CARD_ARCHIVED', 'CARD_RESTORED', 'COMMENT_ADDED', 'COMMENT_EDITED', 'COMMENT_DELETED', 'ATTACHMENT_ADDED', 'ATTACHMENT_DELETED', name='eventtype'), nullable=False))
    op.add_column('events', sa.Column('message', sa.Text(), nullable=False))
    op.create_index(op.f('ix_events_card_id'), 'events', ['card_id'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_foreign_key(None, 'events', 'users', ['user_id'], ['user_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'events', 'cards', ['card_id'], ['id'], ondelete='CASCADE')
    op.drop_column('events', 'entity_id')
    op.drop_column('events', 'event')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('entity_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_card_id'), table_name='events')
    op.drop_column('events', 'message')
    op.drop_column('events', 'event_type')
    op.drop_column('events', 'card_id')
    op.drop_column('events', 'user_id')
    op.execute("DROP TYPE eventtype")
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_user_id_fkey'), 'comments', 'users', ['user_id'], ['user_id'])
    op.drop_column('cards', 'is_archived')
    # ### end Alembic commands ###
